export default {
  spacings: {
    xsmall: '0.8rem',
    small: '1.6rem',
    medium: '2.4rem',
    large: '3.2rem',
    xlarge: '4.0rem',
    huge: '5.6rem',
  },
  colors: {
    primary: '#FCCD2A',
    secondary: '#1E5084',
    tertiary: '#707070',
    warning: '#FAAD14',
    success: '#52C41A',
    error: '#CC1010',
    white: '#fff',
    black: '#000',
    gray: '#E8E8E8',
  },
  border: {
    radius: {
      small: '0.2rem',
      default: '0.4rem',
      large: '1rem',
      huge: '2rem',
    },
  },
  transitions: {
    default: '0.3s ease-in-out',
    quick: '0.1s ease-in-out',
  },
  fonts: {
    family: {
      default: "'Poppins', sans-serif",
    },
    weight: {
      regular: 400,
      medium: 500,
      semiBold: 600,
      bold: 700,
    },
    sizes: {
      xsmall: '1.2rem',
      small: '1.4rem',
      subtitle: '1.6rem',
      medium: '1.8rem',
      large: '2.0rem',
      xlarge: '2.4rem',
      xxlarge: '3.0rem',
      huge: '3.8rem',
    },
    lineHeight: {
      xxsmall: '1.6rem',
      xsmall: '2rem',
      small: '2.2rem',
      medium: '2.4rem',
      large: '2.8rem',
      xlarge: '3.2rem',
      xxlarge: '3.8rem',
    },
    spacings: {
      xsmall: '0.8rem',
      small: '1.6rem',
      medium: '2.4rem',
      large: '3.2rem',
      xlarge: '4.0rem',
      xxlarge: '4.8rem',
      huge: '5.6rem',
      xhuge: '6.4rem',
    },
  },
} as const;
